//
//  DLSAuxiliaryConstraintInformation.h
//  Dials
//
//  Created by Akiva Leffert on 9/27/15.
//  Copyright © 2015 Akiva Leffert. All rights reserved.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@protocol DLSSourceLocation;

/// Contains information generated by a <code>DLSConstraintInformer</code>.
/// Used to transmit additional information about a constraint
/// to a desktop side plugin.
@protocol DLSAuxiliaryConstraintInformation <NSObject, NSCoding>

/// Unique identifier of the plugin that informer that generated this data.
/// Should correspond to a desktop side plugin implementing the <code>ConstraintPlugin</code> protocol.
@property (readonly, copy, nonatomic) NSString* pluginIdentifier;

/// Whether this information can be saved back to the code
@property (readonly, assign, nonatomic) BOOL supportsSaving;

/// Location in code the associated constraint comes from
@property (readonly, strong, nonatomic, nullable) id <DLSSourceLocation> location;

@end

NS_ASSUME_NONNULL_END
